cart/urls.py
# -*- coding: utf-8 -*- 
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.cart_detail, name='cart_detail'),
  url(r'^add/(?P<product_id>\d+)/$',  views.cart_add,  name='cart_add'),
  url(r'^remove/(?P<product_id>\d+)/$',  views.cart_remove,  name='cart_remove'),
]

myshop/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
	url(r'^cart/', include('cart.urls', namespace='cart')),
	url(r'^orders/', include('orders.urls', namespace='orders')),
	url(r'^', include('shop.urls', namespace='shop')),
]

orders/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^create/$',	views.order_create,	name='order_create'),
]

shop/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<category_slug>[-\w]+)/$',views.product_list,name='product_list_by_category'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',views.product_detail,name='product_detail'),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from shop.models import Product

class Order(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50)
	email = models.EmailField()
	address = models.CharField(max_length=250)
	postal_code = models.CharField(max_length=20)
	city = models.CharField(max_length=100)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	paid = models.BooleanField(default=False)
	class Meta:
		ordering = ('-created',)
	def __str__(self):
		return 'Order {}'.format(self.id)
	def get_total_cost(self):
		return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
	order = models.ForeignKey(Order, related_name='items') 
	product = models.ForeignKey(Product,related_name='order_items') 
	price = models.DecimalField(max_digits=10, decimal_places=2)
	quantity = models.PositiveIntegerField(default=1)
	def __str__(self):
		return '{}'.format(self.id)
	def get_cost(self):
		return self.price * self.quantity

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Category(models.Model):
  name = models.CharField(max_length=200,db_index=True)
  slug = models.SlugField(max_length=200,db_index=True,unique=True)
  class Meta:
    ordering = ('name',)
    verbose_name = 'category'
    verbose_name_plural = 'categories'
  def __str__(self):
    return self.name

def get_absolute_url(self):
  return reverse('shop:product_list_by_category',args=[self.slug])

class Product(models.Model):
  category = models.ForeignKey(Category,related_name='products')#produkt ma jedna kategorie//kategoria ma wiele produktow
  name = models.CharField(max_length=200, db_index=True)
  slug = models.SlugField(max_length=200, db_index=True)
  image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
  description = models.TextField(blank=True)
  #decimal_places = 2     = 2 liczby po przecinku
  price = models.DecimalField(max_digits=10, decimal_places=2) 
  stock = models.PositiveIntegerField()
  available = models.BooleanField(default=True)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
  
  class Meta:
    ordering = ('name',)
    index_together = (('id', 'slug'),)
    def __str__(self):
      return self.name
  def get_absolute_url(self):
    return reverse('shop:product_detail',args=[self.id, self.slug])

cart/forms.py
# -*- coding: utf-8 -*-
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
	# coerce konwersja danych wejściowych na postać liczby całkowitej
	quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,coerce=int)
	update = forms.BooleanField(required=False,	initial=False,widget=forms.HiddenInput)

orders/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

cart/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

from django.shortcuts import render, redirect, get_object_or_404 
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

#widok sluzacy do dodawania produktów do koszyka lub uaktualnianai ilosci produktów
# zezwalamy jedynie na żądania POST 
@require_POST
def cart_add(request, product_id):
	print("card_add")
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		print("herj")
		cd = form.cleaned_data
		cart.add(product=product,	quantity=cd['quantity'],	update_quantity=cd['update'])
	return redirect('cart:cart_detail')

def cart_remove(request, product_id):
	print("views cart remove")
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	#pobranie bierzącego koszyka
	cart = Cart(request)
	for item in cart:
		#initial = podane wartosci poczatkowe formularza ? 
		item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
	return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from .tasks import order_created

def order_create(request):
	print("oc")
	cart = Cart(request)
	if request.method == 'POST':
		form = OrderCreateForm(request.POST)
		if form.is_valid():
			order = form.save()
			for item in cart:
				OrderItem.objects.create(order=order,product=item['product'],price=item['price'],quantity=item['quantity'])
			# Usunięcie zawartości koszyka na zakupy.
			cart.clear()
			order_created.delay(order.id)
			return render(request,'orders/order/created.html',{'order': order})
	else:
		form = OrderCreateForm()
	return render(request,'orders/order/create.html',{'cart': cart, 'form': form})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None):
  category = None
  categories = Category.objects.all()
  products = Product.objects.filter(available=True)
  if category_slug:
    category = get_object_or_404(Category, slug=category_slug)
    products = products.filter(category=category)
  return render(request,'shop/product/list.html',{'category': category,'categories': categories,'products': products})


# slug do wygenerowania URLu
def product_detail(request, id, slug):
  product = get_object_or_404(Product,id=id,slug=slug,available=True)
  cart_product_form = CartAddProductForm()
  return render(request,'shop/product/detail.html',{'product': product, 'cart_product_form':cart_product_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
 Koszyk na zakupy
{% endblock %}
{% block content %}
 <h1>Koszyk na zakupy</h1>
 <table class="cart">
   <thead>
     <tr>
       <th>Obraz</th>
       <th>Produkt</th>
       <th>Ilość</th>
       <th>Usuń</th>
       <th>Cena jednostkowa</th>
       <th>Kwota</th>
     </tr>
   </thead>
   <tbody>
     {% for item in cart %}
       {% with product=item.product %}
         <tr>
           <td>
             <a href="{{ product.get_absolute_url }}">
               <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"> </a>
           </td>
           <td>{{ product.name }}</td>
           <td>
				<form action="{% url "cart:cart_add" product.id %}" method="post">
					{{ item.update_quantity_form.quantity }}
					{{ item.update_quantity_form.update }}
					<input type="submit" value="Zmień">
					{% csrf_token %}
				 </form>
		   </td>
           <td><a href="{% url "cart:cart_remove" product.id %}">Usuń</a></td>
           <td class="num">{{ item.price }} zł</td>
           <td class="num">{{ item.total_price }} zł</td>
         </tr>
       {% endwith %}
     {% endfor %}
     <tr class="total">
       <td>Wartość całkowita</td>
       <td colspan="4"></td>
       <td class="num">{{ cart.get_total_price }} zł</td>
     </tr>
   </tbody>
 </table>
 <p class="text-right">
   <a href="{% url "shop:product_list" %}" class="buttonlight">Kontynuuj zakupy</a>
    <a href="{% url "orders:order_create" %}" class="button">
		Do kasy
	</a>
 </p>
{% endblock %}

orders/templates/orders/order/create.html
{% extends "shop/base.html" %}
{% block title %}
 Kasa
{% endblock %}
{% block content %}
 <h1>Kasa</h1>
 <div class="order-info">
   <h3>Zamówienie</h3>
   <ul>
     {% for item in cart %}
       <li>
         {{ item.quantity }}x {{ item.product.name }}
         <span>{{ item.total_price }} zł</span>
       </li>
     {% endfor %}
   </ul>
   <p>Wartość całkowita: {{ cart.get_total_price }} zł</p>
 </div>
 <form action="." method="post" class="order-form">
   {{ form.as_p }}
   <p><input type="submit" value="Złóż zamówienie"></p>
   {% csrf_token %}
 </form>
{% endblock %}

orders/templates/orders/order/created.html
{% extends "shop/base.html" %}
{% block title %}
	Dziękujemy!
{% endblock %}
{% block content %}
<h1>Dziękujemy!</h1>
	<p>
		Zamówienie zostało złożone, a jego numer to <strong>{{ order.id }}</strong>.
	</p>
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
 <meta charset="utf-8" />
 <title>{% block title %}Mój sklep{% endblock %}</title>
 <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
 <div id="header">
   <a href="/" class="logo">Mój sklep</a>
 </div>
 <div id="subheader">
  <div class="cart"> 
   {% with total_items=cart|length %}

     {% if cart|length > 0 %}
       Koszyk:
       <a href="{% url "cart:cart_detail" %}">
         {{ total_items }} produkt{{ total_items|pluralize:"y" }},
         {{ cart.get_total_price }} zł
        
       </a>
     {% else %}
       Koszyk jest pusty.
     {% endif %}
   {% endwith %}
   </div>
 </div>
 <div id="content">
    {% block content %}
   {% endblock %}
 </div>
</body>
</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
	{% if category %}
		{{ category.title }}
	{% else %}
		Produkty
	{% endif %}
{% endblock %}

{% block content %}

	<div class="product-detail">
		<img src="{% if product.image %}
				      {{ product.image.url }}
			      {% else %} 
				      {% static "img/no_image.png" %}{% endif %}">
		<h1>{{ product.name }}</h1>
		
		<h2>
			<a href="{{ product.category.get_absolute_url }}">
				{{ product.category }}
			</a>
		</h2>

		<p class="price">{{ product.price }} zł</p>
			{{ product.description|linebreaks }}

		<form action="{% url "cart:cart_add" product.id %}" method="post"> 
			{{ cart_product_form.as_p }}
			{% csrf_token %}
			<input type="submit" value="Dodaj do koszyka">
		</form>
	</div>
{% endblock %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}

  {% if category %}
    {{ category.name }}
  {% else %}
    Produkty
  {% endif %}

{% endblock %}

{% block content %}
  <div id="sidebar">
   <h3>Kategorie</h3>
   <ul>
     
     <li {% if not category %}class="selected"{% endif %}>
       <a href="{% url "shop:product_list" %}">Wszystkie</a>
     </li>

     {% for c in categories %}
       <li {% if category.slug == c.slug %}class="selected"{% endif %}>
         <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
       </li>
     {% endfor %}
  
  </ul> 
  </div>
  
  <div id="main" class="product-list">
  
    <h1>{% if category %}{{ category.name }}{% else %}Produkty{% endif %}</h1> 
    {% for product in products %}
  
    <div class="item">
      <a href="{{ product.get_absolute_url }}">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}"> 
      </a>
      <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
       {{ product.price }} zł
    </div>
  
    {% endfor %}
  
  </div>

{% endblock %}